# Generated by Django 4.2 on 2023-04-11 21:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0004_tipo_alter_usuario_options_alter_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('identificacion', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('fecha_registro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('edad', models.PositiveIntegerField(default=0)),
                ('stado', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Piloto',
                'verbose_name_plural': 'Pilotos',
                'db_table': 'Pilotos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_despegue', models.TimeField()),
                ('hora_aterrizaje', models.TimeField()),
                ('duracion_minutos', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('creado_por', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='bitacora.piloto')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'VUelos',
                'db_table': 'Vuelos',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='type',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
