# Generated by Django 4.2 on 2023-04-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0007_rename_stado_piloto_estado_remove_piloto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={'ordering': ['id'], 'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.AlterField(
            model_name='piloto',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', null=True, upload_to='avatar/%Y/%m/%d'),
        ),
        migrations.RenameField(
            model_name='piloto',
            old_name='avatar',
            new_name='_avatar',
        ),
    ]
