# Generated by Django 4.2 on 2023-04-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0008_alter_vuelo_options_alter_piloto_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piloto',
            name='_avatar',
        ),
        migrations.AddField(
            model_name='piloto',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
