# Generated by Django 4.2 on 2023-04-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0009_remove_piloto__avatar_piloto_avatar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='piloto',
            table=None,
        ),
    ]
