# Generated by Django 4.2 on 2023-04-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0010_alter_piloto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='piloto',
            table='Pilotos',
        ),
    ]
