# Generated by Django 4.2 on 2023-04-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0011_alter_piloto_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piloto',
            name='avatar',
        ),
    ]
